apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort  # reachable from outside the cluster, via `minikube service frontend`
  selector:
    app: frontend
  ports:
    - port: 8501
      targetPort: 8501
